In [5]:
pip install gradio

Note: you may need to restart the kernel to use updated packages.


In [6]:
import pandas as pd
import numpy as np
import gradio as gr

In [7]:
def greet(name):
    return "Hello " + name + "!"

iface = gr.Interface(fn = greet,inputs = "text",outputs = "text")
iface.launch()

Running on local URL:  http://127.0.0.1:7861/

To create a public link, set `share=True` in `launch()`.


(<gradio.routes.App at 0x2ddc41c96d0>, 'http://127.0.0.1:7861/', None)

In [8]:
df = pd.read_csv('Crop_recommendation.csv')
df.head()

N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [9]:
df.describe()

N            P            K  temperature     humidity  \
count  2200.000000  2200.000000  2200.000000  2200.000000  2200.000000   
mean     50.551818    53.362727    48.149091    25.616244    71.481779   
std      36.917334    32.985883    50.647931     5.063749    22.263812   
min       0.000000     5.000000     5.000000     8.825675    14.258040   
25%      21.000000    28.000000    20.000000    22.769375    60.261953   
50%      37.000000    51.000000    32.000000    25.598693    80.473146   
75%      84.250000    68.000000    49.000000    28.561654    89.948771   
max     140.000000   145.000000   205.000000    43.675493    99.981876   

                ph     rainfall  
count  2200.000000  2200.000000  
mean      6.469480   103.463655  
std       0.773938    54.958389  
min       3.504752    20.211267  
25%       5.971693    64.551686  
50%       6.425045    94.867624  
75%       6.923643   124.267508  
max       9.935091   298.560117

In [10]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [11]:
df.shape

(2200, 8)

In [12]:
df.dtypes

N                int64
P                int64
K                int64
temperature    float64
humidity       float64
ph             float64
rainfall       float64
label           object
dtype: object

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()
df['label'] = le.fit_transform(df['label']);

In [15]:
df.head()

N   P   K  temperature   humidity        ph    rainfall  label
0  90  42  43    20.879744  82.002744  6.502985  202.935536     20
1  85  58  41    21.770462  80.319644  7.038096  226.655537     20
2  60  55  44    23.004459  82.320763  7.840207  263.964248     20
3  74  35  40    26.491096  80.158363  6.980401  242.864034     20
4  78  42  42    20.130175  81.604873  7.628473  262.717340     20

In [16]:
Y = df.drop(df.iloc[:,0:7],axis = 1);

In [17]:
X = df.drop('label',axis = 1)
X

N   P   K  temperature   humidity        ph    rainfall
0      90  42  43    20.879744  82.002744  6.502985  202.935536
1      85  58  41    21.770462  80.319644  7.038096  226.655537
2      60  55  44    23.004459  82.320763  7.840207  263.964248
3      74  35  40    26.491096  80.158363  6.980401  242.864034
4      78  42  42    20.130175  81.604873  7.628473  262.717340
...   ...  ..  ..          ...        ...       ...         ...
2195  107  34  32    26.774637  66.413269  6.780064  177.774507
2196   99  15  27    27.417112  56.636362  6.086922  127.924610
2197  118  33  30    24.131797  67.225123  6.362608  173.322839
2198  117  32  34    26.272418  52.127394  6.758793  127.175293
2199  104  18  30    23.603016  60.396475  6.779833  140.937041

[2200 rows x 7 columns]

In [18]:
Y

label
0        20
1        20
2        20
3        20
4        20
...     ...
2195      5
2196      5
2197      5
2198      5
2199      5

[2200 rows x 1 columns]

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X = X.to_numpy()


In [21]:
X

array([[ 90.        ,  42.        ,  43.        , ...,  82.00274423,
          6.50298529, 202.9355362 ],
       [ 85.        ,  58.        ,  41.        , ...,  80.31964408,
          7.03809636, 226.6555374 ],
       [ 60.        ,  55.        ,  44.        , ...,  82.3207629 ,
          7.84020714, 263.9642476 ],
       ...,
       [118.        ,  33.        ,  30.        , ...,  67.22512329,
          6.36260785, 173.3228386 ],
       [117.        ,  32.        ,  34.        , ...,  52.12739421,
          6.75879255, 127.1752928 ],
       [104.        ,  18.        ,  30.        , ...,  60.39647474,
          6.77983261, 140.9370415 ]])

In [22]:
Y = Y.to_numpy()
Y

array([[20],
       [20],
       [20],
       ...,
       [ 5],
       [ 5],
       [ 5]])

In [23]:
Y.shape

(2200, 1)

In [24]:
Y = np.reshape(Y, (1,np.product(Y.shape)))

In [25]:
Y.shape

(1, 2200)

In [26]:
Y

array([[20, 20, 20, ...,  5,  5,  5]])

In [27]:
Y = Y.flatten()

In [28]:
Y

array([20, 20, 20, ...,  5,  5,  5])

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 42);

In [31]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [32]:
random_forest = RandomForestClassifier(n_estimators=1000)
random_forest.fit(X_train, Y_train)

Y_pred_RF = random_forest.predict(X_test)
acc = accuracy_score(Y_test,Y_pred_RF);
print(acc)

0.9931818181818182


In [33]:
from sklearn.neighbors import KNeighborsClassifier

In [34]:
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(X_train, Y_train) 
Y_pred_KNN = knn.predict(X_test)
acc = accuracy_score(Y_test,Y_pred_KNN)
print(acc)

0.9704545454545455


In [35]:
from sklearn.tree import DecisionTreeClassifier

In [36]:
decision_tree = DecisionTreeClassifier()
decision_tree.fit(X_train, Y_train)
Y_pred_DT = decision_tree.predict(X_test)
acc = accuracy_score(Y_test,Y_pred_DT)
print(acc)

0.9886363636363636


In [37]:
from sklearn.naive_bayes import GaussianNB

In [38]:
gaussian = GaussianNB()
gaussian.fit(X_train, Y_train) 
Y_pred_GNB = gaussian.predict(X_test)
acc = accuracy_score(Y_test,Y_pred_GNB)
print(acc)

0.9954545454545455


In [39]:
from sklearn.ensemble import VotingClassifier

model_hard = VotingClassifier(estimators=[('rf',random_forest),('GNB', gaussian),('DT', decision_tree),('KNN', knn)], voting='hard')

In [40]:
model_hard

VotingClassifier(estimators=[('rf', RandomForestClassifier(n_estimators=1000)),
                             ('GNB', GaussianNB()),
                             ('DT', DecisionTreeClassifier()),
                             ('KNN', KNeighborsClassifier(n_neighbors=3))])

In [41]:
model_hard.fit(X_train,Y_train)

VotingClassifier(estimators=[('rf', RandomForestClassifier(n_estimators=1000)),
                             ('GNB', GaussianNB()),
                             ('DT', DecisionTreeClassifier()),
                             ('KNN', KNeighborsClassifier(n_neighbors=3))])

In [42]:
ans_pred=model_hard.predict(X_test)

In [43]:
accuracy_ensemble = accuracy_score(Y_test,ans_pred)
accuracy_ensemble

0.9931818181818182

In [44]:
model_soft = VotingClassifier(estimators=[('rf',random_forest),('GNB', gaussian),('DT', decision_tree),('KNN', knn)], voting='soft')

In [46]:
model_soft.fit(X_train,Y_train)

VotingClassifier(estimators=[('rf', RandomForestClassifier(n_estimators=1000)),
                             ('GNB', GaussianNB()),
                             ('DT', DecisionTreeClassifier()),
                             ('KNN', KNeighborsClassifier(n_neighbors=3))],
                 voting='soft')

In [63]:
soft_pred = model_soft.predict(X_test)
X_test[0]

array([101.        ,  17.        ,  47.        ,  29.49401389,
        94.72981338,   6.18505323,  26.30820876])

In [68]:
soft_acc = accuracy_score(Y_test,soft_pred)
soft_acc

0.990909090909091

In [81]:
def funct(Nitrogen,Phosphorous,Potassium,Temperature,Humidity,pH,Rainfall):
    soft = model_soft.predict([[Nitrogen,Phosphorous,Potassium,Temperature,Humidity,pH,Rainfall]])
    crop = le.inverse_transform(soft)
    
    return "The best suitable crop is: " + crop[0]


iface = gr.Interface(fn = funct,inputs = [gr.inputs.Number(),gr.inputs.Number(),gr.inputs.Number(),gr.inputs.Number(label = "Temperature in degree Celsius"),gr.inputs.Number(),gr.inputs.Slider(0,14,label = "pH"),gr.inputs.Number()],outputs = "text")
iface.launch()


D:\Anaconda3\lib\site-packages\gradio\inputs.py:58: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
D:\Anaconda3\lib\site-packages\gradio\deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
D:\Anaconda3\lib\site-packages\gradio\inputs.py:88: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(


Running on local URL:  http://127.0.0.1:7866/

To create a public link, set `share=True` in `launch()`.


(<gradio.routes.App at 0x2ddcee90640>, 'http://127.0.0.1:7866/', None)